spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
   console:
     enabled: true
     settings:
       web-allow-others: false


