server:
  port: 5555
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
            allowedMethods:
              - GET
              - POST
            allowedHeaders:
              - Authorization
              - Cache-Control
              - Content-Type
              - username
      routes:
        - id: core-service
          uri: http://localhost:8080/core-market/
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/core-market
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8089/cart-market
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/cart-market
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8190/auth-market
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/auth-market
            - JwtAuthFilter
jwt:
  secret: adfkjasbflkjahgkj;ahglkjagbljkadfgbakjghajkfahfagag

