server:
  port: 8089
  servlet:
    context-path: /cart-market
integrations:
  product-service:
    url: http://localhost:8080/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000



