server:
  port: 8080
  servlet:
    context-path: /core-market
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
   console:
     enabled: true
     settings:
       web-allow-others: false
integrations:
  cart-service:
    url: http://localhost:8089/cart-market/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000


